### ISSUE TITLE
Repo configs changes are not updated to deployment

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/rm-configs#11]
Recent changes to UCSD and Kreonet DTNs on the repo have not shown up in model. We may still have problem with the auto-update mechanism.

**Comment by juztas** [comment]
Fixed here: https://github.com/sdn-sense/siterm/commit/d82d00ae5c7ce1cf89578b01be4b069add49e1a0
New release released. Forced run cron on UCSD - Agents got new release right away and fix in place. As I dont have access to Kreonet - if Kreonet was installed with auto-update option - it will update in next 6hours (cronjob timing)

**Comment by xi-yang** [comment]
Is auto-update optional? How is it activated? 

6 hours is a bit too long. 30 minutes might be good.

**Comment by juztas** [comment]
code does not change so often to do it every 30mins. It is a cron, so it is
always activated:
https://github.com/sdn-sense/siterm/blob/master/packaging/dtnrm-site-fe/siterm-crons#L7

Sites can disable auto update by setting this flag (either in agent or fe):
general:
  autoupdate: false
