### ISSUE TITLE
Verify CENIC_PW_LAX site configs

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/rm-configs#3]
1. K8s/k8s-siterm.yaml: What is the K8s (Worker) node name for the DTN?
```
NodeSelector: irnc-dtn02.mgmt.lax.pw.cenic.net
```

2. K8s/k8s-script.sh: Update the `MASTER_NODE_PATH` that will have the SSL cert and private key when available. 

The cert is for the DTN (worker node) but must be placed on the K8s maser node for deployment. 

3. FE/auth.yaml: needs DN of the SSL cert to relate the `??`
```
cenic_pw_lax:
  full_dn: ??
  permissions: w
```

4. Agent01/main.yaml: Verify the public interface name 
```
  PUBLIC_INTF: ens1
```

5. Make sure GitHub and Dockerhub repos are accessible from the PacificWave K8s cluster. 
* `https://github.com/sdn-sense/rm-configs`
* docker hub: sdnsense/site-rm-sense
* docker hub: sdnsense/site-agent-sense

**Comment by juztas** [comment]
I would suggest to rename dir to `T3_US_CENIC_PW_LAX` - there are some regex depend on this.

DN - must be `$ISSUER$FULL_DN`. you could get the following info with `openssl x509 -in $CERTFILE -text -noout`

For interface - this needs to be checked with John

**Comment by xi-yang** [comment]
Changed into `T3_US_PW_LAX `.

John will get cert from InCommon.

**Comment by juztas** [comment]
We will need to upload Incommon CA here too:
https://github.com/sdn-sense/rm-configs/tree/master/CAs

**Comment by juztas** [comment]
Can we close this?

**Comment by xi-yang** [comment]
@
